### PR TITLE
Update keycloak to latest version

### PR DESCRIPTION
**Pull request by waseem-h**

### CODE REVIEW

**Comment by stakater-user** [comment]
@waseem-h Chart: keycloak Dry Run successful

**Comment by stakater-user** [comment]
@waseem-h Chart: keycloak Dry Run successful

**Comment by stakater-user** [comment]
@waseem-h Chart: keycloak-db Dry Run successful

**Comment by stakater-user** [comment]
@waseem-h Chart: keycloak-db Dry Run successful

**Comment by stakater-user** [comment]
@waseem-h Chart: keycloak-db-storage Dry Run successful

**Comment by stakater-user** [comment]
@waseem-h Chart: keycloak-db-storage Dry Run successful

**Review by kahootali — APPROVED** [review]

**Pull request merged**
